### ISSUE TITLE
Getting wrong winner for test bams

### ISSUE THREAD

**Issue by ghost** [jason-weirather/hla-solver#14]
Hi! Thank you for the hla-polysolver program! When I was running the test bam files, here's what I got: winners1	hla_a_01_01_01_01	hla_b_07_02_01	hla_c_01_02_01 for both alleles. I followed the exact same steps in your instruction. Could you give a suggestion of what might went wrong?

**Comment by jason-weirather** [comment]
Hi @MaXXinee i address this in the Readme

> ⚠ Please note that this fork of polysolver does not produce exactly the same HLA haplotype calls as the example file included with polysolver. I observed one difference in the haplotype, but I think it was in one of the more minor subtype of one of the haplotypes.

As per Readme i always recommend executing the author's or polysolvers docker if you possibly can

https://hub.docker.com/r/sachet/polysolver/tags/ 

this package was only developed to execute the 1.0 software (not current) in an environment we were required to use where we could not use docker.  Sorry I don't have more details on the nuance of the difference, but the 1.0 software didn't run out of the box and required some work to get it going so I don't know if its reference differences or component version differences, or something else like parameter differences between what produced the original test and whats done here to account for the differences.
